In [446]:
import numpy as np
import pandas as pd

In [447]:
books = pd.read_csv('Books.csv', low_memory=False)

In [448]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [449]:
books.shape

(271360, 8)

In [450]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [451]:
books = books.drop('Image-URL-S', axis=1, errors='ignore')
books = books.drop('Image-URL-M', axis=1, errors='ignore')

books = books.drop('Image-URL-L', axis=1, errors='ignore')

books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [452]:
users = pd.read_csv('Users.csv', low_memory=False)
ratings = pd.read_csv('Ratings.csv', low_memory=False)

In [453]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [454]:
print(ratings.shape)
print(users.shape)
print(books.shape)

(1149780, 3)
(278858, 3)
(271360, 5)

In [455]:
ratings['User-ID'].value_counts()

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [456]:
x=ratings['User-ID'].value_counts()>200

In [457]:
x[x].shape

(899,)

In [458]:
y=x[x].index

In [459]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='User-ID', length=899)

In [460]:
ratings=ratings[ratings['User-ID'].isin(y)]

In [461]:
ratings.head()

      User-ID        ISBN  Book-Rating
1456   277427  002542730X           10
1457   277427  0026217457            0
1458   277427  003008685X            8
1459   277427  0030615321            0
1460   277427  0060002050            0

In [462]:
ratings.shape

(526356, 3)

In [463]:
ratings_books=ratings.merge(books,on="ISBN")

In [464]:
ratings_books.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books

In [465]:
num_ratings=ratings_books.groupby('Book-Title')['Book-Rating'].count().reset_index()

In [466]:
num_ratings.head()

                                          Book-Title  Book-Rating
0   A Light in the Storm: The Civil War Diary of ...            2
1                              Always Have Popsicles            1
2               Apple Magic (The Collector's series)            1
3   Beyond IBM: Leadership Marketing and Finance ...            1
4   Clifford Visita El Hospital (Clifford El Gran...            1

In [467]:
num_ratings.rename(columns={'Book-Rating':'num_of_ratings'},inplace=True)

In [468]:
final_rating=ratings_books.merge(num_ratings,on='Book-Title')

In [469]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,num_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,13

In [470]:
final_rating=final_rating[final_rating['num_of_ratings']>=50]

In [471]:
final_rating.drop_duplicates(['User-ID','Book-Title'],inplace=True)

In [472]:
final_rating.shape

(59850, 8)

In [473]:
book_pivot=final_rating.pivot_table(columns='User-ID',index='Book-Title',values='Book-Rating')

In [474]:
book_pivot

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [475]:
from scipy.sparse import csr_matrix

In [476]:

book_pivot = book_pivot.fillna(0)  # Replace NaN values with 0

book_sparse=csr_matrix(book_pivot)

In [544]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='ball_tree')

In [546]:
model.fit(book_sparse)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py:584: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

NearestNeighbors(algorithm='ball_tree')

In [548]:
# distance,suggestion=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [552]:
from sklearn.model_selection import train_test_split

# Split data into training and test sets
train_data, test_data = train_test_split(book_pivot, test_size=0.2, random_state=42)

# Fill missing values in training data
train_data = train_data.fillna(0)
test_data = test_data.fillna(0)
# Convert training data to sparse matrix
train_sparse = csr_matrix(train_data)

# Fit the model
model.fit(train_sparse)
test_index = 0  # Choose a sample from test data
test_sparse = csr_matrix(test_data)

# Find similar items
distances, indices = model.kneighbors(test_sparse[test_index], n_neighbors=5)

# Retrieve recommendations
recommended_books = train_data.index[indices.flatten()]
print("Recommendations:", recommended_books)

Recommendations: Index(['No Safe Place', 'Homeport', 'The Little Friend', 'Long After Midnight',
       'Exclusive'],
      dtype='object', name='Book-Title')

In [554]:
pip install scikit-learn scipy

Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\lib\site-packages (1.4.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (1.13.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

In [555]:
def mean_average_precision(recommended, relevant):
    average_precisions = []
    for rec, rel in zip(recommended, relevant):
        if not rel:
            continue
        precisions = []
        num_hits = 0
        for i, item in enumerate(rec):
            if item in rel:
                num_hits += 1
                precisions.append(num_hits / (i + 1))
        average_precisions.append(sum(precisions) / len(rel))
    return sum(average_precisions) / len(average_precisions)

# Example usage
recommended = [[1, 2, 3], [4, 5, 6]]
relevant = [[2, 3], [5, 7]]
print("MAP:", mean_average_precision(recommended, relevant))

MAP: 0.41666666666666663

In [556]:
import numpy as np

def ndcg(recommended, relevant, k=10):
    def dcg(recommended, relevant, k):
        recommended = recommended[:k]
        gain = [1 if item in relevant else 0 for item in recommended]
        discounts = [np.log2(i + 2) for i in range(len(gain))]
        return sum([g / d for g, d in zip(gain, discounts)])

    scores = []
    for rec, rel in zip(recommended, relevant):
        idcg = dcg(rel, rel, k)  # Ideal DCG
        actual_dcg = dcg(rec, rel, k)
        scores.append(actual_dcg / idcg if idcg > 0 else 0)
    return np.mean(scores)

# Example usage
print("NDCG:", ndcg(recommended, relevant, k=3))

NDCG: 0.5401396054259062

In [557]:
def mean_reciprocal_rank(recommended, relevant):
    reciprocal_ranks = []
    for rec, rel in zip(recommended, relevant):
        for rank, item in enumerate(rec):
            if item in rel:
                reciprocal_ranks.append(1 / (rank + 1))
                break
        else:
            reciprocal_ranks.append(0)
    return sum(reciprocal_ranks) / len(reciprocal_ranks)

# Example usage
print("MRR:", mean_reciprocal_rank(recommended, relevant))

MRR: 0.5